language: go
go: '1.11.x'
install: make setup
script:
  - make ci
  - ./org-stats --org goreleaser --blacklist get --top 10
after_success:
  - go get github.com/mattn/goveralls
  - goveralls -coverprofile=coverage.out -service=travis-ci -repotoken="$COVERALLS_TOKEN"
deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
notifications:
  email: false
